apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: kustomize-

resources:
- guestbook-ui-deployment.yaml
- guestbook-ui-svc.yaml

configMapGenerator:
- name: guestbook-ui-map
  literals:
    - altGreeting=Good Morning!
    - enableRisky="false"
    - aNewKey=a new value
